### PR TITLE
Fix #34

### LINKED ISSUE #34: Callback implementation
I'm trying to simulate a driven, self coupled laser and wanted to utilise callbacks for the driving. Are callback not implemented for SDDEs yet, or am I doing something wrong?

Julia v1.4.2
StochasticDelayDiffEq v0.2.5

Simplified example of what I'm trying to do, which works fine without the callback:

```
using StochasticDelayDiffEq

delay(u, h, p, t) = 0.3 * h(p, t-p)
stoc(u, h, p, t) = 0.1
h(p, t) = 0.;

p = 0.5
tspan = (0.0, 4.0)
lags = [p];

prob = SDDEProblem(
    delay,
    stoc,
    h,
    tspan,
    p;
    constant_lags=lags
);

condition(u,t,integrator) = t == 3
affect!(integrator) = integrator.u -= 0.3
cb = DiscreteCallback(condition, affect!)

sol = solve(prob, RKMil(), tstops=[3]);
cb_sol = solve(prob, RKMil(), tstops=[3], callback=cb);
```

The last line returns `u_modified!: method has not been implemented for the integrator`.

Thank you for the great work so far, I'm just getting into Julia because of this package!

### PR DESCRIPTION
**Pull request by devmotion**
Fixes #34.

### CODE REVIEW

File: src/integrators/interface.jl [hunk 1]
```diff
@@ -221,8 +221,28 @@ end
...
+    if integrator.P !== nothing && integrator.opts.adaptive
+        if integrator.cache isa StochasticDiffEqMutableCache
+            oldrate = integrator.P.cache.currate
+            integrator.P.cache.rate(oldrate, integrator.u, integrator.p, integrator.t)
+        else
+            integrator.P.cache.currate = integrator.P.cache.rate(
+                integrator.u, integrator.p, integrator.t
+            )
+        end
+    end
```
Comment (devmotion) [inline src/integrators/interface.jl:236]: The original code in StochasticDiffEq is incorrect (unqualified `u`, `p`, `t`, and `P`), it seems it is not tested properly.
